"""Type stub for the real llm_sdk package (see PLACEHOLDER.md).

This .pyi file is only read by static type checkers (mypy); Python itself
ignores it at runtime and will import the real implementation once it is
copied into this directory, as required by the assignment.
"""

from typing import Any

class Small_LLM_Model:
    def __init__(self) -> None: ...
    def get_logits_from_input_ids(self, input_ids: Any) -> Any: ...
    def get_path_to_vocabulary_json(self) -> str: ...
    def encode(self, text: str) -> list[int]: ...
    def decode(self, token_ids: list[int]) -> str: ...
